/*
-- Query: select * from virtucon_db.workers_worker
LIMIT 0, 1000

-- Date: 2022-07-09 20:11
*/
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (1,'Douglas','Evil','Dr. Evil','Dr._Evil.png',1000000,'1967-01-01','dr-evil@virtucon.com','5556666',1,1,NULL,'It\'s  *DR.*  Evil. I didn\'t spend 6 years in Evil Medical School to be called \'mister\', thank you very much');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (2,'Robert','Wagner','Number 2','2.png',500000,'1967-01-01','2@virtucon.com','5552222',2,2,1,'There is no world anymore. It\'s only corporations');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (3,'Frau','Farbissina','','Farbissina.png',350000,'1967-01-01','frau@virtucon.com','5551933',3,2,1,'Bring in the ^*%&^*!');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (4,'Mustafa','Ali','Mustafa','Mustafa.png',500000,'1996-02-29','mustafa@virtucon.com','5559283',4,2,1,' I can\'t stand to be asked the same question 3 times. It just irritates me');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (5,'Ted','Bigglesworth','Mr. Bigglesworth','Bigglesworth.png',400000,'1967-01-01','meow@virtucon.com','5558465',1,13,1,'Meow. Meow, meow, meow');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (6,'Scott','Evil','','Scott_Evil.png',900000,'1997-05-02','scott@virtucon.com','5559365',1,3,1,'I wish I was never artificially created in a lab');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (7,'Verne','Evil','Mini-Me','Mini-Me.png',950000,'1999-05-08','minime@virtucon.com','5550000',1,4,1,'*Weird incomprehensible murmurs*');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (8,'Mike','Myers','Fat Bastard','Fat_Bastard.png',250000,'1999-05-02','baby-eater@virtucon.com','5559999',3,5,3,'I want my baby-back ribs');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (9,'Paddy','O\'Brien','','OBrien.png',250000,'1997-05-02','lucky@virtucon.com','5557693',3,5,3,'They\'re always after me lucky charms');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (10,'Joe','Son','Random Task','Random_Task.png',250000,'1997-05-02','random@virtucon.com','5558469',3,5,3,'Less talking, more shoe throwing');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (11,'Bryan','Danielson','','Danielson.png',5300,'2022-01-01','bryan@virtucon.com','5559274',3,6,3,'Please open your bag, sir');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (12,'Harry','Mcguire','','Mcguire.png',5300,'2022-01-01','Harry@virtucon.com','5559364',3,6,3,'I like Backgammon');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (13,'Neal','Brannan','','Brannan.png',5300,'2022-01-01','neal@virtucon.com','5553292',3,6,3,'Security First!');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (14,'Henry','Paul','','Paul.png',110000,'2012-05-20','henry@virtucon.com','5552094',2,7,2,'Rule #1: Never lose money. Rule #2: Don\'t forget rule #1');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (15,'Richard','Ford','','Ford.png',95000,'1995-12-05','richie@virtucon.com','5550378',2,8,2,'Stocks are the man\'s best friends. I hate dogs');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (16,'Kevin','Steen','','Steen.png',30000,'2021-11-19','kevin@virtucon.com','5551209',2,9,2,'Your wish is my command');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (17,'Robert','Kelly','','Kelly.png',20000,'2022-03-14','bobby@virtucon.com','5556730',4,10,4,'I\'m afraid of the mossad');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (18,'Diane','Fitzgerald','','Fitzgerald.png',14000,'2003-07-07','diane@virtucon.com','5551250',4,11,4,'We can explode it!');
INSERT INTO `` (`id`,`first_name`,`last_name`,`professional_name`,`profile_pic`,`salary`,`hire_date`,`email`,`phone`,`department_id`,`job_id`,`manager_id`,`personal_motto`) VALUES (19,'Albert','Anderson','','Anderson.png',20000,'1967-01-01','albert@virtucon.com','5559327',4,12,4,'Don\'t forget your sweater');
