# Generated by Django 4.0.4 on 2022-06-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'managed': False},
        ),
    ]
