# Generated by Django 4.0.4 on 2022-06-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_department_options_alter_job_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='workers_department',
        ),
        migrations.AlterModelTable(
            name='job',
            table='workers_job',
        ),
    ]
