# Generated by Django 4.0.4 on 2022-06-22 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_department_table_alter_job_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('professional_name', models.CharField(blank=True, max_length=255)),
                ('profile_pic', models.ImageField(default='', upload_to='')),
                ('salary', models.IntegerField()),
                ('hire_date', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=7, unique=True)),
                ('department', models.ForeignKey(default='General', on_delete=django.db.models.deletion.SET_DEFAULT, to='workers.department')),
                ('job', models.ForeignKey(default='Confidential', on_delete=django.db.models.deletion.SET_DEFAULT, to='workers.job')),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='workers.worker')),
                ('team_members', models.ManyToManyField(to='workers.worker')),
            ],
        ),
    ]
