# Generated by Django 4.0.4 on 2022-06-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_department_options_alter_job_options_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='team_members',
            field=models.ManyToManyField(blank=True, to='workers.worker'),
        ),
        migrations.AlterModelTable(
            name='department',
            table=None,
        ),
        migrations.AlterModelTable(
            name='job',
            table=None,
        ),
    ]
