# Generated by Django 4.0.4 on 2022-06-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_alter_worker_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='short_bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
