# Generated by Django 4.0.4 on 2022-06-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_worker_short_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='short_bio',
        ),
        migrations.AddField(
            model_name='worker',
            name='personal_motto',
            field=models.CharField(default='', max_length=255),
        ),
    ]
