# Generated by Django 4.0.4 on 2022-07-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_remove_worker_short_bio_worker_personal_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='personal_motto',
            field=models.CharField(default='', max_length=120),
        ),
    ]
